url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/uptodate" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-paginate
paginate: 4
paginate_path: /page:num/
